// <auto-generated />
namespace SourceControlFinalAssignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class commit10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(commit10));
        
        string IMigrationMetadata.Id
        {
            get { return "202012151328598_commit1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
